// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graph.proto

#include "graph.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace opencv_tensorflow {
class GraphDefDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE::internal::ExplicitlyConstructed<GraphDef>
      _instance;
} _GraphDef_default_instance_;
class NodeDef_AttrEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE::internal::ExplicitlyConstructed<NodeDef_AttrEntry_DoNotUse>
      _instance;
} _NodeDef_AttrEntry_DoNotUse_default_instance_;
class NodeDefDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE::internal::ExplicitlyConstructed<NodeDef>
      _instance;
} _NodeDef_default_instance_;
}  // namespace opencv_tensorflow
namespace protobuf_graph_2eproto {
void InitDefaultsGraphDefImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::PROTOBUF_NAMESPACE::internal::InitProtobufDefaultsForceUnique();
#else
  ::PROTOBUF_NAMESPACE::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_graph_2eproto::InitDefaultsNodeDef();
  protobuf_versions_2eproto::InitDefaultsVersionDef();
  protobuf_function_2eproto::InitDefaultsFunctionDefLibrary();
  {
    void* ptr = &::opencv_tensorflow::_GraphDef_default_instance_;
    new (ptr) ::opencv_tensorflow::GraphDef();
    ::PROTOBUF_NAMESPACE::internal::OnShutdownDestroyMessage(ptr);
  }
  ::opencv_tensorflow::GraphDef::InitAsDefaultInstance();
}

void InitDefaultsGraphDef() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::PROTOBUF_NAMESPACE::GoogleOnceInit(&once, &InitDefaultsGraphDefImpl);
}

void InitDefaultsNodeDef_AttrEntry_DoNotUseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::PROTOBUF_NAMESPACE::internal::InitProtobufDefaultsForceUnique();
#else
  ::PROTOBUF_NAMESPACE::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_attr_5fvalue_2eproto::InitDefaultsAttrValue();
  {
    void* ptr = &::opencv_tensorflow::_NodeDef_AttrEntry_DoNotUse_default_instance_;
    new (ptr) ::opencv_tensorflow::NodeDef_AttrEntry_DoNotUse();
  }
  ::opencv_tensorflow::NodeDef_AttrEntry_DoNotUse::InitAsDefaultInstance();
}

void InitDefaultsNodeDef_AttrEntry_DoNotUse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::PROTOBUF_NAMESPACE::GoogleOnceInit(&once, &InitDefaultsNodeDef_AttrEntry_DoNotUseImpl);
}

void InitDefaultsNodeDefImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::PROTOBUF_NAMESPACE::internal::InitProtobufDefaultsForceUnique();
#else
  ::PROTOBUF_NAMESPACE::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_graph_2eproto::InitDefaultsNodeDef_AttrEntry_DoNotUse();
  {
    void* ptr = &::opencv_tensorflow::_NodeDef_default_instance_;
    new (ptr) ::opencv_tensorflow::NodeDef();
    ::PROTOBUF_NAMESPACE::internal::OnShutdownDestroyMessage(ptr);
  }
  ::opencv_tensorflow::NodeDef::InitAsDefaultInstance();
}

void InitDefaultsNodeDef() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::PROTOBUF_NAMESPACE::GoogleOnceInit(&once, &InitDefaultsNodeDefImpl);
}

::PROTOBUF_NAMESPACE::Metadata file_level_metadata[3];

const ::PROTOBUF_NAMESPACE::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::GraphDef, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::GraphDef, node_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::GraphDef, versions_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::GraphDef, version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::GraphDef, library_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::NodeDef_AttrEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::NodeDef_AttrEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::NodeDef_AttrEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::NodeDef_AttrEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::NodeDef, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::NodeDef, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::NodeDef, op_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::NodeDef, input_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::NodeDef, device_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::opencv_tensorflow::NodeDef, attr_),
};
static const ::PROTOBUF_NAMESPACE::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::opencv_tensorflow::GraphDef)},
  { 9, 16, sizeof(::opencv_tensorflow::NodeDef_AttrEntry_DoNotUse)},
  { 18, -1, sizeof(::opencv_tensorflow::NodeDef)},
};

static ::PROTOBUF_NAMESPACE::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE::Message*>(&::opencv_tensorflow::_GraphDef_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE::Message*>(&::opencv_tensorflow::_NodeDef_AttrEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE::Message*>(&::opencv_tensorflow::_NodeDef_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::PROTOBUF_NAMESPACE::MessageFactory* factory = NULL;
  AssignDescriptors(
      "graph.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::PROTOBUF_NAMESPACE::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::PROTOBUF_NAMESPACE::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013graph.proto\022\021opencv_tensorflow\032\020attr_v"
      "alue.proto\032\016function.proto\032\016versions.pro"
      "to\"\262\001\n\010GraphDef\022(\n\004node\030\001 \003(\0132\032.opencv_t"
      "ensorflow.NodeDef\022/\n\010versions\030\004 \001(\0132\035.op"
      "encv_tensorflow.VersionDef\022\023\n\007version\030\003 "
      "\001(\005B\002\030\001\0226\n\007library\030\002 \001(\0132%.opencv_tensor"
      "flow.FunctionDefLibrary\"\301\001\n\007NodeDef\022\014\n\004n"
      "ame\030\001 \001(\t\022\n\n\002op\030\002 \001(\t\022\r\n\005input\030\003 \003(\t\022\016\n\006"
      "device\030\004 \001(\t\0222\n\004attr\030\005 \003(\0132$.opencv_tens"
      "orflow.NodeDef.AttrEntry\032I\n\tAttrEntry\022\013\n"
      "\003key\030\001 \001(\t\022+\n\005value\030\002 \001(\0132\034.opencv_tenso"
      "rflow.AttrValue:\0028\001B,\n\030org.tensorflow.fr"
      "ameworkB\013GraphProtosP\001\370\001\001b\006proto3"
  };
  ::PROTOBUF_NAMESPACE::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 513);
  ::PROTOBUF_NAMESPACE::MessageFactory::InternalRegisterGeneratedFile(
    "graph.proto", &protobuf_RegisterTypes);
  ::protobuf_attr_5fvalue_2eproto::AddDescriptors();
  ::protobuf_function_2eproto::AddDescriptors();
  ::protobuf_versions_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::PROTOBUF_NAMESPACE::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_graph_2eproto
namespace opencv_tensorflow {

// ===================================================================

void GraphDef::InitAsDefaultInstance() {
  ::opencv_tensorflow::_GraphDef_default_instance_._instance.get_mutable()->versions_ = const_cast< ::opencv_tensorflow::VersionDef*>(
      ::opencv_tensorflow::VersionDef::internal_default_instance());
  ::opencv_tensorflow::_GraphDef_default_instance_._instance.get_mutable()->library_ = const_cast< ::opencv_tensorflow::FunctionDefLibrary*>(
      ::opencv_tensorflow::FunctionDefLibrary::internal_default_instance());
}
void GraphDef::_slow_mutable_versions() {
  versions_ = ::PROTOBUF_NAMESPACE::Arena::CreateMessage< ::opencv_tensorflow::VersionDef >(
      GetArenaNoVirtual());
}
void GraphDef::unsafe_arena_set_allocated_versions(
    ::opencv_tensorflow::VersionDef* versions) {
  if (GetArenaNoVirtual() == NULL) {
    delete versions_;
  }
  versions_ = versions;
  if (versions) {

  } else {

  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opencv_tensorflow.GraphDef.versions)
}
void GraphDef::clear_versions() {
  if (GetArenaNoVirtual() == NULL && versions_ != NULL) {
    delete versions_;
  }
  versions_ = NULL;
}
void GraphDef::_slow_mutable_library() {
  library_ = ::PROTOBUF_NAMESPACE::Arena::CreateMessage< ::opencv_tensorflow::FunctionDefLibrary >(
      GetArenaNoVirtual());
}
void GraphDef::unsafe_arena_set_allocated_library(
    ::opencv_tensorflow::FunctionDefLibrary* library) {
  if (GetArenaNoVirtual() == NULL) {
    delete library_;
  }
  library_ = library;
  if (library) {

  } else {

  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opencv_tensorflow.GraphDef.library)
}
void GraphDef::clear_library() {
  if (GetArenaNoVirtual() == NULL && library_ != NULL) {
    delete library_;
  }
  library_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GraphDef::kNodeFieldNumber;
const int GraphDef::kVersionsFieldNumber;
const int GraphDef::kVersionFieldNumber;
const int GraphDef::kLibraryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GraphDef::GraphDef()
  : ::PROTOBUF_NAMESPACE::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_graph_2eproto::InitDefaultsGraphDef();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:opencv_tensorflow.GraphDef)
}
GraphDef::GraphDef(::PROTOBUF_NAMESPACE::Arena* arena)
  : ::PROTOBUF_NAMESPACE::Message(),
  _internal_metadata_(arena),
  node_(arena) {
  ::protobuf_graph_2eproto::InitDefaultsGraphDef();
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:opencv_tensorflow.GraphDef)
}
GraphDef::GraphDef(const GraphDef& from)
  : ::PROTOBUF_NAMESPACE::Message(),
      _internal_metadata_(NULL),
      node_(from.node_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_library()) {
    library_ = new ::opencv_tensorflow::FunctionDefLibrary(*from.library_);
  } else {
    library_ = NULL;
  }
  if (from.has_versions()) {
    versions_ = new ::opencv_tensorflow::VersionDef(*from.versions_);
  } else {
    versions_ = NULL;
  }
  version_ = from.version_;
  // @@protoc_insertion_point(copy_constructor:opencv_tensorflow.GraphDef)
}

void GraphDef::SharedCtor() {
  ::memset(&library_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&version_) -
      reinterpret_cast<char*>(&library_)) + sizeof(version_));
  _cached_size_ = 0;
}

GraphDef::~GraphDef() {
  // @@protoc_insertion_point(destructor:opencv_tensorflow.GraphDef)
  SharedDtor();
}

void GraphDef::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == NULL);
  if (this != internal_default_instance()) delete library_;
  if (this != internal_default_instance()) delete versions_;
}

void GraphDef::ArenaDtor(void* object) {
  GraphDef* _this = reinterpret_cast< GraphDef* >(object);
  (void)_this;
}
void GraphDef::RegisterArenaDtor(::PROTOBUF_NAMESPACE::Arena* arena) {
}
void GraphDef::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::PROTOBUF_NAMESPACE::Descriptor* GraphDef::descriptor() {
  ::protobuf_graph_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_graph_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GraphDef& GraphDef::default_instance() {
  ::protobuf_graph_2eproto::InitDefaultsGraphDef();
  return *internal_default_instance();
}

GraphDef* GraphDef::New(::PROTOBUF_NAMESPACE::Arena* arena) const {
  return ::PROTOBUF_NAMESPACE::Arena::CreateMessage<GraphDef>(arena);
}

void GraphDef::Clear() {
// @@protoc_insertion_point(message_clear_start:opencv_tensorflow.GraphDef)
  ::PROTOBUF_NAMESPACE::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  node_.Clear();
  if (GetArenaNoVirtual() == NULL && library_ != NULL) {
    delete library_;
  }
  library_ = NULL;
  if (GetArenaNoVirtual() == NULL && versions_ != NULL) {
    delete versions_;
  }
  versions_ = NULL;
  version_ = 0;
  _internal_metadata_.Clear();
}

bool GraphDef::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE::uint32 tag;
  // @@protoc_insertion_point(parse_start:opencv_tensorflow.GraphDef)
  for (;;) {
    ::std::pair< ::PROTOBUF_NAMESPACE::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .opencv_tensorflow.NodeDef node = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE::uint8>(tag) ==
            static_cast< ::PROTOBUF_NAMESPACE::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::PROTOBUF_NAMESPACE::internal::WireFormatLite::ReadMessage(input, add_node()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .opencv_tensorflow.FunctionDefLibrary library = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE::uint8>(tag) ==
            static_cast< ::PROTOBUF_NAMESPACE::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::PROTOBUF_NAMESPACE::internal::WireFormatLite::ReadMessage(
               input, mutable_library()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 version = 3 [deprecated = true];
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE::uint8>(tag) ==
            static_cast< ::PROTOBUF_NAMESPACE::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::PROTOBUF_NAMESPACE::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE::int32, ::PROTOBUF_NAMESPACE::internal::WireFormatLite::TYPE_INT32>(
                 input, &version_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .opencv_tensorflow.VersionDef versions = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE::uint8>(tag) ==
            static_cast< ::PROTOBUF_NAMESPACE::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::PROTOBUF_NAMESPACE::internal::WireFormatLite::ReadMessage(
               input, mutable_versions()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:opencv_tensorflow.GraphDef)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:opencv_tensorflow.GraphDef)
  return false;
#undef DO_
}

void GraphDef::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:opencv_tensorflow.GraphDef)
  ::PROTOBUF_NAMESPACE::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .opencv_tensorflow.NodeDef node = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->node_size()); i < n; i++) {
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->node(static_cast<int>(i)), output);
  }

  // .opencv_tensorflow.FunctionDefLibrary library = 2;
  if (this->has_library()) {
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->library_, output);
  }

  // int32 version = 3 [deprecated = true];
  if (this->version() != 0) {
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteInt32(3, this->version(), output);
  }

  // .opencv_tensorflow.VersionDef versions = 4;
  if (this->has_versions()) {
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->versions_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::PROTOBUF_NAMESPACE::internal::GetProto3PreserveUnknownsDefault())) {
    ::PROTOBUF_NAMESPACE::internal::WireFormat::SerializeUnknownFields(
        (::PROTOBUF_NAMESPACE::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:opencv_tensorflow.GraphDef)
}

::PROTOBUF_NAMESPACE::uint8* GraphDef::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::PROTOBUF_NAMESPACE::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:opencv_tensorflow.GraphDef)
  ::PROTOBUF_NAMESPACE::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .opencv_tensorflow.NodeDef node = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->node_size()); i < n; i++) {
    target = ::PROTOBUF_NAMESPACE::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->node(static_cast<int>(i)), deterministic, target);
  }

  // .opencv_tensorflow.FunctionDefLibrary library = 2;
  if (this->has_library()) {
    target = ::PROTOBUF_NAMESPACE::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, *this->library_, deterministic, target);
  }

  // int32 version = 3 [deprecated = true];
  if (this->version() != 0) {
    target = ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteInt32ToArray(3, this->version(), target);
  }

  // .opencv_tensorflow.VersionDef versions = 4;
  if (this->has_versions()) {
    target = ::PROTOBUF_NAMESPACE::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, *this->versions_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::PROTOBUF_NAMESPACE::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::PROTOBUF_NAMESPACE::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::PROTOBUF_NAMESPACE::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:opencv_tensorflow.GraphDef)
  return target;
}

size_t GraphDef::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:opencv_tensorflow.GraphDef)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::PROTOBUF_NAMESPACE::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::PROTOBUF_NAMESPACE::internal::WireFormat::ComputeUnknownFieldsSize(
        (::PROTOBUF_NAMESPACE::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .opencv_tensorflow.NodeDef node = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->node_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::PROTOBUF_NAMESPACE::internal::WireFormatLite::MessageSize(
          this->node(static_cast<int>(i)));
    }
  }

  // .opencv_tensorflow.FunctionDefLibrary library = 2;
  if (this->has_library()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::MessageSize(
        *this->library_);
  }

  // .opencv_tensorflow.VersionDef versions = 4;
  if (this->has_versions()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::MessageSize(
        *this->versions_);
  }

  // int32 version = 3 [deprecated = true];
  if (this->version() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::Int32Size(
        this->version());
  }

  int cached_size = ::PROTOBUF_NAMESPACE::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GraphDef::MergeFrom(const ::PROTOBUF_NAMESPACE::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:opencv_tensorflow.GraphDef)
  GOOGLE_DCHECK_NE(&from, this);
  const GraphDef* source =
      ::PROTOBUF_NAMESPACE::internal::DynamicCastToGenerated<const GraphDef>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:opencv_tensorflow.GraphDef)
    ::PROTOBUF_NAMESPACE::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:opencv_tensorflow.GraphDef)
    MergeFrom(*source);
  }
}

void GraphDef::MergeFrom(const GraphDef& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:opencv_tensorflow.GraphDef)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  node_.MergeFrom(from.node_);
  if (from.has_library()) {
    mutable_library()->::opencv_tensorflow::FunctionDefLibrary::MergeFrom(from.library());
  }
  if (from.has_versions()) {
    mutable_versions()->::opencv_tensorflow::VersionDef::MergeFrom(from.versions());
  }
  if (from.version() != 0) {
    set_version(from.version());
  }
}

void GraphDef::CopyFrom(const ::PROTOBUF_NAMESPACE::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:opencv_tensorflow.GraphDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GraphDef::CopyFrom(const GraphDef& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:opencv_tensorflow.GraphDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GraphDef::IsInitialized() const {
  return true;
}

void GraphDef::Swap(GraphDef* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    GraphDef* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void GraphDef::UnsafeArenaSwap(GraphDef* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void GraphDef::InternalSwap(GraphDef* other) {
  using std::swap;
  node_.InternalSwap(&other->node_);
  swap(library_, other->library_);
  swap(versions_, other->versions_);
  swap(version_, other->version_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::PROTOBUF_NAMESPACE::Metadata GraphDef::GetMetadata() const {
  protobuf_graph_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_graph_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

NodeDef_AttrEntry_DoNotUse::NodeDef_AttrEntry_DoNotUse() {}
NodeDef_AttrEntry_DoNotUse::NodeDef_AttrEntry_DoNotUse(::PROTOBUF_NAMESPACE::Arena* arena) : SuperType(arena) {}
void NodeDef_AttrEntry_DoNotUse::MergeFrom(const NodeDef_AttrEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE::Metadata NodeDef_AttrEntry_DoNotUse::GetMetadata() const {
  ::protobuf_graph_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_graph_2eproto::file_level_metadata[1];
}
void NodeDef_AttrEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE::Message& other) {
  ::PROTOBUF_NAMESPACE::Message::MergeFrom(other);
}


// ===================================================================

void NodeDef::InitAsDefaultInstance() {
}
void NodeDef::clear_attr() {
  attr_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NodeDef::kNameFieldNumber;
const int NodeDef::kOpFieldNumber;
const int NodeDef::kInputFieldNumber;
const int NodeDef::kDeviceFieldNumber;
const int NodeDef::kAttrFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NodeDef::NodeDef()
  : ::PROTOBUF_NAMESPACE::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_graph_2eproto::InitDefaultsNodeDef();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:opencv_tensorflow.NodeDef)
}
NodeDef::NodeDef(::PROTOBUF_NAMESPACE::Arena* arena)
  : ::PROTOBUF_NAMESPACE::Message(),
  _internal_metadata_(arena),
  input_(arena),
  attr_(arena) {
  ::protobuf_graph_2eproto::InitDefaultsNodeDef();
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:opencv_tensorflow.NodeDef)
}
NodeDef::NodeDef(const NodeDef& from)
  : ::PROTOBUF_NAMESPACE::Message(),
      _internal_metadata_(NULL),
      input_(from.input_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  attr_.MergeFrom(from.attr_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.Set(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited(), from.name(),
      GetArenaNoVirtual());
  }
  op_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited());
  if (from.op().size() > 0) {
    op_.Set(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited(), from.op(),
      GetArenaNoVirtual());
  }
  device_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited());
  if (from.device().size() > 0) {
    device_.Set(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited(), from.device(),
      GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(copy_constructor:opencv_tensorflow.NodeDef)
}

void NodeDef::SharedCtor() {
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited());
  op_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited());
  device_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

NodeDef::~NodeDef() {
  // @@protoc_insertion_point(destructor:opencv_tensorflow.NodeDef)
  SharedDtor();
}

void NodeDef::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == NULL);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited());
  op_.DestroyNoArena(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited());
  device_.DestroyNoArena(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited());
}

void NodeDef::ArenaDtor(void* object) {
  NodeDef* _this = reinterpret_cast< NodeDef* >(object);
  (void)_this;
}
void NodeDef::RegisterArenaDtor(::PROTOBUF_NAMESPACE::Arena* arena) {
}
void NodeDef::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::PROTOBUF_NAMESPACE::Descriptor* NodeDef::descriptor() {
  ::protobuf_graph_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_graph_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NodeDef& NodeDef::default_instance() {
  ::protobuf_graph_2eproto::InitDefaultsNodeDef();
  return *internal_default_instance();
}

NodeDef* NodeDef::New(::PROTOBUF_NAMESPACE::Arena* arena) const {
  return ::PROTOBUF_NAMESPACE::Arena::CreateMessage<NodeDef>(arena);
}

void NodeDef::Clear() {
// @@protoc_insertion_point(message_clear_start:opencv_tensorflow.NodeDef)
  ::PROTOBUF_NAMESPACE::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  input_.Clear();
  attr_.Clear();
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  op_.ClearToEmpty(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  device_.ClearToEmpty(&::PROTOBUF_NAMESPACE::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  _internal_metadata_.Clear();
}

bool NodeDef::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE::uint32 tag;
  // @@protoc_insertion_point(parse_start:opencv_tensorflow.NodeDef)
  for (;;) {
    ::std::pair< ::PROTOBUF_NAMESPACE::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE::uint8>(tag) ==
            static_cast< ::PROTOBUF_NAMESPACE::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::PROTOBUF_NAMESPACE::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::PROTOBUF_NAMESPACE::internal::WireFormatLite::PARSE,
            "opencv_tensorflow.NodeDef.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string op = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE::uint8>(tag) ==
            static_cast< ::PROTOBUF_NAMESPACE::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::PROTOBUF_NAMESPACE::internal::WireFormatLite::ReadString(
                input, this->mutable_op()));
          DO_(::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
            this->op().data(), static_cast<int>(this->op().length()),
            ::PROTOBUF_NAMESPACE::internal::WireFormatLite::PARSE,
            "opencv_tensorflow.NodeDef.op"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string input = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE::uint8>(tag) ==
            static_cast< ::PROTOBUF_NAMESPACE::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::PROTOBUF_NAMESPACE::internal::WireFormatLite::ReadString(
                input, this->add_input()));
          DO_(::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
            this->input(this->input_size() - 1).data(),
            static_cast<int>(this->input(this->input_size() - 1).length()),
            ::PROTOBUF_NAMESPACE::internal::WireFormatLite::PARSE,
            "opencv_tensorflow.NodeDef.input"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string device = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE::uint8>(tag) ==
            static_cast< ::PROTOBUF_NAMESPACE::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::PROTOBUF_NAMESPACE::internal::WireFormatLite::ReadString(
                input, this->mutable_device()));
          DO_(::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
            this->device().data(), static_cast<int>(this->device().length()),
            ::PROTOBUF_NAMESPACE::internal::WireFormatLite::PARSE,
            "opencv_tensorflow.NodeDef.device"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, .opencv_tensorflow.AttrValue> attr = 5;
      case 5: {
        if (static_cast< ::PROTOBUF_NAMESPACE::uint8>(tag) ==
            static_cast< ::PROTOBUF_NAMESPACE::uint8>(42u /* 42 & 0xFF */)) {
          NodeDef_AttrEntry_DoNotUse::Parser< ::PROTOBUF_NAMESPACE::internal::MapField<
              NodeDef_AttrEntry_DoNotUse,
              ::std::string, ::opencv_tensorflow::AttrValue,
              ::PROTOBUF_NAMESPACE::internal::WireFormatLite::TYPE_STRING,
              ::PROTOBUF_NAMESPACE::internal::WireFormatLite::TYPE_MESSAGE,
              0 >,
            ::PROTOBUF_NAMESPACE::Map< ::std::string, ::opencv_tensorflow::AttrValue > > parser(&attr_);
          DO_(::PROTOBUF_NAMESPACE::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::PROTOBUF_NAMESPACE::internal::WireFormatLite::PARSE,
            "opencv_tensorflow.NodeDef.AttrEntry.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:opencv_tensorflow.NodeDef)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:opencv_tensorflow.NodeDef)
  return false;
#undef DO_
}

void NodeDef::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:opencv_tensorflow.NodeDef)
  ::PROTOBUF_NAMESPACE::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::SERIALIZE,
      "opencv_tensorflow.NodeDef.name");
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // string op = 2;
  if (this->op().size() > 0) {
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
      this->op().data(), static_cast<int>(this->op().length()),
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::SERIALIZE,
      "opencv_tensorflow.NodeDef.op");
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->op(), output);
  }

  // repeated string input = 3;
  for (int i = 0, n = this->input_size(); i < n; i++) {
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
      this->input(i).data(), static_cast<int>(this->input(i).length()),
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::SERIALIZE,
      "opencv_tensorflow.NodeDef.input");
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteString(
      3, this->input(i), output);
  }

  // string device = 4;
  if (this->device().size() > 0) {
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
      this->device().data(), static_cast<int>(this->device().length()),
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::SERIALIZE,
      "opencv_tensorflow.NodeDef.device");
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->device(), output);
  }

  // map<string, .opencv_tensorflow.AttrValue> attr = 5;
  if (!this->attr().empty()) {
    typedef ::PROTOBUF_NAMESPACE::Map< ::std::string, ::opencv_tensorflow::AttrValue >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE::internal::WireFormatLite::SERIALIZE,
          "opencv_tensorflow.NodeDef.AttrEntry.key");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->attr().size() > 1) {
      ::PROTOBUF_NAMESPACE::scoped_array<SortItem> items(
          new SortItem[this->attr().size()]);
      typedef ::PROTOBUF_NAMESPACE::Map< ::std::string, ::opencv_tensorflow::AttrValue >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE::Map< ::std::string, ::opencv_tensorflow::AttrValue >::const_iterator
          it = this->attr().begin();
          it != this->attr().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::PROTOBUF_NAMESPACE::scoped_ptr<NodeDef_AttrEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(attr_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteMessageMaybeToArray(
            5, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::PROTOBUF_NAMESPACE::scoped_ptr<NodeDef_AttrEntry_DoNotUse> entry;
      for (::PROTOBUF_NAMESPACE::Map< ::std::string, ::opencv_tensorflow::AttrValue >::const_iterator
          it = this->attr().begin();
          it != this->attr().end(); ++it) {
        entry.reset(attr_.NewEntryWrapper(
            it->first, it->second));
        ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteMessageMaybeToArray(
            5, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::PROTOBUF_NAMESPACE::internal::GetProto3PreserveUnknownsDefault())) {
    ::PROTOBUF_NAMESPACE::internal::WireFormat::SerializeUnknownFields(
        (::PROTOBUF_NAMESPACE::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:opencv_tensorflow.NodeDef)
}

::PROTOBUF_NAMESPACE::uint8* NodeDef::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::PROTOBUF_NAMESPACE::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:opencv_tensorflow.NodeDef)
  ::PROTOBUF_NAMESPACE::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::SERIALIZE,
      "opencv_tensorflow.NodeDef.name");
    target =
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // string op = 2;
  if (this->op().size() > 0) {
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
      this->op().data(), static_cast<int>(this->op().length()),
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::SERIALIZE,
      "opencv_tensorflow.NodeDef.op");
    target =
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteStringToArray(
        2, this->op(), target);
  }

  // repeated string input = 3;
  for (int i = 0, n = this->input_size(); i < n; i++) {
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
      this->input(i).data(), static_cast<int>(this->input(i).length()),
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::SERIALIZE,
      "opencv_tensorflow.NodeDef.input");
    target = ::PROTOBUF_NAMESPACE::internal::WireFormatLite::
      WriteStringToArray(3, this->input(i), target);
  }

  // string device = 4;
  if (this->device().size() > 0) {
    ::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
      this->device().data(), static_cast<int>(this->device().length()),
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::SERIALIZE,
      "opencv_tensorflow.NodeDef.device");
    target =
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::WriteStringToArray(
        4, this->device(), target);
  }

  // map<string, .opencv_tensorflow.AttrValue> attr = 5;
  if (!this->attr().empty()) {
    typedef ::PROTOBUF_NAMESPACE::Map< ::std::string, ::opencv_tensorflow::AttrValue >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE::internal::WireFormatLite::SERIALIZE,
          "opencv_tensorflow.NodeDef.AttrEntry.key");
      }
    };

    if (deterministic &&
        this->attr().size() > 1) {
      ::PROTOBUF_NAMESPACE::scoped_array<SortItem> items(
          new SortItem[this->attr().size()]);
      typedef ::PROTOBUF_NAMESPACE::Map< ::std::string, ::opencv_tensorflow::AttrValue >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE::Map< ::std::string, ::opencv_tensorflow::AttrValue >::const_iterator
          it = this->attr().begin();
          it != this->attr().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::PROTOBUF_NAMESPACE::scoped_ptr<NodeDef_AttrEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(attr_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::PROTOBUF_NAMESPACE::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       5, *entry, deterministic, target);
;
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::PROTOBUF_NAMESPACE::scoped_ptr<NodeDef_AttrEntry_DoNotUse> entry;
      for (::PROTOBUF_NAMESPACE::Map< ::std::string, ::opencv_tensorflow::AttrValue >::const_iterator
          it = this->attr().begin();
          it != this->attr().end(); ++it) {
        entry.reset(attr_.NewEntryWrapper(
            it->first, it->second));
        target = ::PROTOBUF_NAMESPACE::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       5, *entry, deterministic, target);
;
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::PROTOBUF_NAMESPACE::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::PROTOBUF_NAMESPACE::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::PROTOBUF_NAMESPACE::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:opencv_tensorflow.NodeDef)
  return target;
}

size_t NodeDef::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:opencv_tensorflow.NodeDef)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::PROTOBUF_NAMESPACE::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::PROTOBUF_NAMESPACE::internal::WireFormat::ComputeUnknownFieldsSize(
        (::PROTOBUF_NAMESPACE::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string input = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE::internal::FromIntSize(this->input_size());
  for (int i = 0, n = this->input_size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE::internal::WireFormatLite::StringSize(
      this->input(i));
  }

  // map<string, .opencv_tensorflow.AttrValue> attr = 5;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE::internal::FromIntSize(this->attr_size());
  {
    ::PROTOBUF_NAMESPACE::scoped_ptr<NodeDef_AttrEntry_DoNotUse> entry;
    for (::PROTOBUF_NAMESPACE::Map< ::std::string, ::opencv_tensorflow::AttrValue >::const_iterator
        it = this->attr().begin();
        it != this->attr().end(); ++it) {
      if (entry.get() != NULL && entry->GetArena() != NULL) {
        entry.release();
      }
      entry.reset(attr_.NewEntryWrapper(it->first, it->second));
      total_size += ::PROTOBUF_NAMESPACE::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
    if (entry.get() != NULL && entry->GetArena() != NULL) {
      entry.release();
    }
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string op = 2;
  if (this->op().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::StringSize(
        this->op());
  }

  // string device = 4;
  if (this->device().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE::internal::WireFormatLite::StringSize(
        this->device());
  }

  int cached_size = ::PROTOBUF_NAMESPACE::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NodeDef::MergeFrom(const ::PROTOBUF_NAMESPACE::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:opencv_tensorflow.NodeDef)
  GOOGLE_DCHECK_NE(&from, this);
  const NodeDef* source =
      ::PROTOBUF_NAMESPACE::internal::DynamicCastToGenerated<const NodeDef>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:opencv_tensorflow.NodeDef)
    ::PROTOBUF_NAMESPACE::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:opencv_tensorflow.NodeDef)
    MergeFrom(*source);
  }
}

void NodeDef::MergeFrom(const NodeDef& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:opencv_tensorflow.NodeDef)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  input_.MergeFrom(from.input_);
  attr_.MergeFrom(from.attr_);
  if (from.name().size() > 0) {
    set_name(from.name());
  }
  if (from.op().size() > 0) {
    set_op(from.op());
  }
  if (from.device().size() > 0) {
    set_device(from.device());
  }
}

void NodeDef::CopyFrom(const ::PROTOBUF_NAMESPACE::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:opencv_tensorflow.NodeDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NodeDef::CopyFrom(const NodeDef& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:opencv_tensorflow.NodeDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NodeDef::IsInitialized() const {
  return true;
}

void NodeDef::Swap(NodeDef* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    NodeDef* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void NodeDef::UnsafeArenaSwap(NodeDef* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void NodeDef::InternalSwap(NodeDef* other) {
  using std::swap;
  input_.InternalSwap(&other->input_);
  attr_.Swap(&other->attr_);
  name_.Swap(&other->name_);
  op_.Swap(&other->op_);
  device_.Swap(&other->device_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::PROTOBUF_NAMESPACE::Metadata NodeDef::GetMetadata() const {
  protobuf_graph_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_graph_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace opencv_tensorflow

// @@protoc_insertion_point(global_scope)
